### ISSUE TITLE
Circuit Breakers monitoring

### ISSUE THREAD

**Issue by tmszdmsk** [jhalterman/failsafe#140]
Problem
======
We want to collect metrics about Circuit Breakers 

Our current approach
================
Circuit Breaker monitoring (open/half-open/closed)
---------------------------------------------------
We've implemented `Failsafe` wrapper that takes `CircuitBreaker` and its `name` and produces `SyncFailsafe` object with the listener (`onOpen`/`onClose`/`onHalfOpen`) that reports metrics automatically attached.

Problem with this approach is that `CircuitBreaker` can have only one of each listener and subsequent `onOpen/...` calls override it so it is error prone solution. It wouldn't be a problem if `CircuitBreaker` was an interface. We could decorate original `CircuitBreaker` with support for multiple listeners pretty easily and in a clean way. Of course, we can try to extend it, but it is not a very elegant solution.

Of course it will be a breaking change as everyone now creates circuit breakers using `new CircuitBreaker()`.

**Comment by MALPI** [comment]
Are you using spring maybe?

**Comment by tmszdmsk** [comment]
nope. why do you ask? :)

**Comment by MALPI** [comment]
For Spring Boot there is [Failsafe Actuator](https://github.com/zalando/failsafe-actuator) that we use for monitoring. But maybe you can re-use the pattern for splitting between monitoring the state and monitoring *other* metrics.

**Comment by whiskeysierra** [comment]
I'm trying to elaborate a bit more on @MALPI's [Failsafe Actuator](https://github.com/zalando/failsafe-actuator). In a nutshell it just exposes all circuit breakers as a management endpoint. We use that in conjunction with our monitoring system [ZMON](https://docs.zmon.io/en/latest/) to periodically get the latest states of all circuit breakers in our application(s). As soon as we detect open/half-open we raise an alert which pops up on our screens etc.

That approach is based on sampling, since we only check for the state every x seconds. For alerting that's good enough for us, since we are in control how often we check and how big the delay is until our alert comes up.

What @tmszdmsk describes is another approach and I actually implemented it the very same way in [Riptide's `MetricsCircuitBreakerListener`](https://github.com/zalando/riptide/blob/master/riptide-failsafe/src/main/java/org/zalando/riptide/failsafe/metrics/MetricsCircuitBreakerListener.java). What it does is to measure the duration per state giving you insights into your application's failure modes. This is helpful if you want to fine-tune your circuit breaker settings.

Coming now to the concrete proposal of this issue:

> Problem with this approach is that CircuitBreaker can have only one of each listener and subsequent onOpen/... calls override it so it is error prone solution.

I believe that's usually not an issue for applications, since they are traditionally in charge of creating the circuit breaker. It will become a problem if you pass it to some other library that you're not controlling.

> It wouldn't be a problem if CircuitBreaker was an interface. We could decorate original CircuitBreaker with support for multiple listeners pretty easily and in a clean way.

I'd propose another way. Instead of decorating the circuit breaker, you can implement a custom composite/compound listener that take a collection of listeners and cycles them. You still won't be able to let some one call `onOpen`/... on your circuit breaker, but you can take someone's listener and actively register it yourself.

**Comment by whiskeysierra** [comment]
I just realized that `CircuitBreaker` is not `final`. Therefore you could subclass it and implement support for multiple listeners yourself. 

@jhalterman Is it intentionally non-final?

**Comment by jhalterman** [comment]
Yep - CircuitBreaker is not final by intention. I'm happy to see it extended and it sure can be.

**Comment by jhalterman** [comment]
I'm not sure what exactly the OP would want out of this issue. I did just merge some metrics related methods into master that expose success and failure counts inside the CircuitBreaker. Closing this for now but feel free to re-open with specific ideas if something else is desired.
