### ISSUE TITLE
Support async fallback execution

### ISSUE THREAD

**Issue by jhalterman** [jhalterman/failsafe#145]

**Comment by jhalterman** [comment]
@ben-manes Did you want just the fallback to be async or the execution as well?

**Comment by ben-manes** [comment]
The execution too. I was chaining the retrials of async calls with fallback to another async call.

In this case, I abandoned AWS S3 sdk v2 because it has been horribly buggy and frustrating for months. However I didn’t want to switch back to v1 just before the holidays and have new problems. So I chained them to call v1 and fallback to v2. I ended up having either finish by populating a future to work around this limitation.

**Comment by jhalterman** [comment]
Any API suggestions for this? I'm thinking of being able to mix sync and async policies:

```java
Failsafe.
  .withAsync(fallback)
  .with(retryPolicy)
  .with(circuitBreaker)
  .getAsync(callable);
```

These would be applied in reverse order, which I know gets back to your previous comment about ordering here not being obvious.

**Comment by ben-manes** [comment]
I didn't put a lot of thought into it, but I was thinking of a more explicit DSL.

I guess you want to reuse the `Failsafe` object, but I wonder how something like `CompletableFuture` would look. A `with` is conventionally used as nicer syntax for unordered builder steps. I wouldn't go as far as a telescoping builder.
```java
Failsafe
    .supplyAsync(callable)
    .andThrottleWith(circuitBreaker)
    .andRetryWith(retryPolicy)
    .execute();
```
but I haven't thought about it more than 15 seconds, so you know much more than me on what makes sense. If you are okay with a backwards incompatible API, I'd replace `with` using more concrete lifecycle names.

**Comment by ben-manes** [comment]
@lukaseder is great at DSLs and jOOQ has a great API, so maybe he can chime in with advice.

**Comment by jhalterman** [comment]
Thanks for the response.

The reason for the current backwards API - config first, execute last - is because it's needed for synchronous executions, where `get` is a terminal method:

```java
Failsafe.with(retryPolicy).get(this::connect);
```

It isn't strictly necessary to do this for the async API, but I stuck with it for the sake of consistency, so the only thing that's different between a sync and async execution could be the terminal method.

The reason I didn't go with more explicit methods like `andRetryWith` is because I want to support user-definable Policies.

I'm mostly wondering about mixing sync and async policy execution. What thread would you like to have a fallback executed on if async?

**Comment by ben-manes** [comment]
> What thread would you like to have a fallback executed on if async?

I would expect it to be performed on the configured executor as a newly enqued task.

**Comment by ben-manes** [comment]
Fairness of letting other work on the executor proceed. If you use overuse a shared executor, like `commonPool`, then it could stall other operations that may be more critical (e.g. user-facing). I don't mind the policy work on the task, since that's probably very quick. But I wouldn't want the thread acquired and used for multiple executions of that task, as that prioritizes it over other pending work.

**Comment by lukaseder** [comment]
> @lukaseder is great at DSLs and jOOQ has a great API, so maybe he can chime in with advice.

Egh, designing jOOQ is straightforward. Is there a SQL clause? So there must be a corresponding method with a 1:1 clause to method name translation... :-)

I might be able to help, but I'd have to catch up with quite a bit of context first... Any TL;DR version, perhaps, @ben-manes ?

**Comment by lukaseder** [comment]
Those issues look similar to what I did with the `org.jooq.Configuration`, which has a couple of `set()` (mutable) and `derive()` (immutable) methods that help building a configuration instance. It can then be wrapped in `DSL.using(Configuration)` to create an entry point for the "configured DSL" (to build executable queries), as opposed to the "static DSL".

Of course, this separation is arbitrary, and has been confusing a few new jOOQ users in the past. Putting the "execution API" on the "configuration API" can work just as well.

I don't recommend doing things like these:

> Failsafe.with(circuitBreaker, retryPolicy, fallback)....

Because it's almost not possible to maintain backwards compatibility. Add a new parameter? You have to deprecate the above method, or overload it. Usually, in the absence of one of the arguments, there's always a very sensible default, so the `with().with().with()` approach usually works best.

I understand that the order of these calls seems to matter. Ideally, it should not, but I don't fully understand what the API is doing yet.

Regarding things like:

> .onRetry(f -> refreshContext())

There's nothing wrong with adding convenience methods to simplify the arguments to the configuration API, as long as it is very "obvious" what parts of the API constitute the "configuration API" and what parts constitute the "execution API". In jOOQ, this is obvious, because they're separate, and the execution API looks a lot like SQL. With failsafe, it may not be that obvious, but it can probably be learned, just like the Java `Stream` API can be learned (where pipeline methods are similar to the "configuration API" and terminal ops are similar to the "execution API")

HTH

**Comment by jhalterman** [comment]
> It can then be wrapped in DSL.using(Configuration) to create an entry point for the "configured DSL" (to build executable queries),

👍 This is similar to the idea behind `Failsafe.with(Policy)`: to give you something that could then be used to execute code with the Policy being applied to results/failures as needed.

> I don't recommend doing things like these:
>```Failsafe.with(circuitBreaker, retryPolicy, fallback)....```
> Because it's almost not possible to maintain backwards compatibility. Add a new parameter? You have to deprecate the above method, or overload it.

I was thinking of having Failsafe.with(Policy<T>...)` take varargs, so I don't think backwards compatibility would be an issue in the future, but varargs generics have their own issues.

> I understand that the order of these calls seems to matter. Ideally, it should not, but I don't fully understand what the API is doing yet.

I agree on the ideally part. Failsafe applies some failure handling policies to an execution result in some order, and it's important that users should be able to specify the order. In practice, it's similar to composing some function calls:

Fallback(RetryPolicy(CircuitBreaker(User-Submitted-Callable)))

Since we're really doing composition here, we could have an API that is explicit about this:

```java
Callable callableWithCircuitBreaker = Failsafe.wrap(callable, circuitBreaker)
Callable callableWithRetryPolicy = Failsafe.wrap(callable, retryPolicy);
Callable callableWithFallback = Failsafe.wrap(callable, fallback);

callableWithFallback.call()....
```

But being able to compose a Failsafe instance with all the policies in one step is a bit nicer. That said, order does matter and essentially we are composing things.

**Comment by Tembrel** [comment]
On the limited question discussed [above](https://github.com/jhalterman/failsafe/issues/145#issuecomment-451712206), about thread execution policies for fallbacks, is the consensus that it is sufficient
- for synchronous gets: to run the fallback in the calling thread, and
- for asynchronous, to submit the fallback action/callable to the configured executor, i.e., the one used for each of the tries of the primary submitted action/callable?

If so, good. That makes things simple.

If not &mdash; i.e., if it's important to be able to specify a different pool for fallback handling, or to use async fallbacks with sync gets or vice versa &mdash; then do folks agree that it would be better to configure a second executor (thread execution policy) for fallbacks than have to specify the executor in each `withFallback` call, causing an explosion of `withFallback` methods?

**Comment by jhalterman** [comment]
> for synchronous gets: to run the fallback in the calling thread, and

Yep

> for asynchronous, to submit the fallback action/callable to the configured executor, i.e., the one used for each of the tries of the primary submitted action/callable?

Using the same executor yes, but not necessarily a separate submission. I'm thinking it would be fine to simply tag the fallback action onto the end of the callable execution as opposed to running it as part of a separate submission. Ben [seems to think that's fine](https://github.com/jhalterman/failsafe/issues/145#issuecomment-451712206) as well.

**Comment by Tembrel** [comment]
Ben (@ben-manes) wrote:
> But I wouldn't want the thread acquired and used for multiple executions of that task, as that prioritizes it over other pending work.

The fallback in general might be just as "heavy" as the retried task, so wouldn't you want to treat it the same?

Also, doesn't tagging/tacking the fallback action onto the end of the last failed try at the callable constrain the implementation to have the control logic in the same thread as the callable execution?

**Comment by jhalterman** [comment]
> The fallback in general might be just as "heavy" as the retried task, so wouldn't you want to treat it the same?

Fair point 👍 Fallback is unlike the other policies (so far) in that way. Similar to the discussion in #162 though, users could always run their fallback asynchronously. Failsafe needs a result from the fallback either way.

> Also, doesn't tagging/tacking the fallback action onto the end of the last failed try at the callable constrain the implementation to have the control logic in the same thread as the callable execution?

Yep, though I don't think that's a problem per se, do you?

**Comment by jhalterman** [comment]
I'm guessing we're good enough with the current approach to policy execution where it follows in the same thread as the runnable/supplier execution, but users can perform on another thread if they wish. Supporting separately configurable executors for specific policies would introduce more complexity than it is probably worth, so I think we're good for now.

**Comment by Tembrel** [comment]
> If users want to kick off another separate thread, they are free to do so from within their fallback impl. 

How would one do this?

**Comment by Tembrel** [comment]
But if that call is made in the thread of the last failed retry, that thread will block.

**Comment by jhalterman** [comment]
I ended up adding some better support (8cd9c9314661f75e0665cc5dfab72e31eb3a1265) for this where a `Fallback` can be declared async when it's created:

```java
Fallback fallback = Fallback.ofAsync(this::connectToBackup);
Failsafe.with(fallback, retryPolicy).get(this::connectToPrimary);
```

This way the execution API stays pretty simple, and indicating whether a Fallback should be async or not is on the fallback itself. TBD whether we should accept a particular scheduler for performing the async fallback on:

```java
Fallback.withAsync(this::connectToBack).with(fallbackScheduler)
```

But I'm happy exclude that for now until it seems necessary.

**Comment by Tembrel** [comment]
You could capture that last case by supplying `ofAsync` variants that return `CompletableFuture<R>` instead of `R`, e.g.,

```java
    public static <R> Fallback<R> ofAsync(Supplier<CompletableFuture<? extends R>> fallback) ...
```

(Don't need checked supplier in this case.)

In fact, maybe it would be best __only__ to offer those variants.

**Comment by jhalterman** [comment]
I like that executing things asynchronously can be done with a simple Supplier<R> since this allow symmetry with the FailsafeExecutor API:

```java
Connection connectToPrimary() {...}
Connection connectToPrimary() {...}

Failsafe.with(Fallback.ofAsync(this::connectToBackup)).getAsync(this::connectToPrimary);
```

Adding CompletableFuture as a separate enhancement in #165.

**Comment by jhalterman** [comment]
@Tembrel The reason I went with `FailsafeExecutor.getStageAsync` instead of `getStage` is because the initial `Supplier.get`, along with subsequent retries, are performed in a separate thread. It wasn't clear to me if this is always strictly necessary, so I left the door open for a `.getStage` (non-async) in the future. Any thoughts on this?

**Comment by Tembrel** [comment]
Oops, sorry, I didn't look closely at #165 before commenting. Ignore that comment. But a few things occur to me now:


### `getStageAsync` vs. `getStage`

About `Supplier.get` being performed in a separate thread. You said it wasn't clear that it's always necessary. I can't imagine that it's __ever__ necessary. I would think that in virtually all cases, the only work done by the supplier is to construct the completable future, and there's no need to execute such a trivial supplier in a different thread.

Since you can implement `getStageAsync` in terms of (proposed for later) `getStage`, but not vice versa, why not just jettison `getStageAsync` and use `getStage` instead?
```java
<T extends R> CompletableFuture<T> getStage(Supplier<? extends CompletionStage<T>> supplier)
```
Note that `CheckedSupplier` is overkill when the thing being supplied is a completable future. The supplier of the __future__ shouldn't be throwing checked exceptions.

The existing `getAsync` could be implemented in terms of `getStage`:
```java
<T extends R> CompletableFuture<T> getAsync(CheckedSupplier<T> supplier) {
    return getStage(() -> supplyAsync(() -> supplier.get()));
}
```
where `supplyAsync` is a wrapper (TBD) around `CompletableFuture.supplyAsync` that takes care of tunneling any exception thrown by the supplier via a `FailsafeException`.

### Naming

*Stage* isn't a great term to use in method names, since it's a bit of a wart that people have to know about `CompletionStage` at all. They should just have to learn about completable future.

**Comment by jhalterman** [comment]
> Since you can implement getStageAsync in terms of (proposed for later) getStage, but not vice versa, why not just jettison getStageAsync and use getStage instead?

Trying this out now. One of the challenges is the internals treat CompletionStage code path for async specifically. Will see what can be done...

> Stage isn't a great term to use in method names, since it's a bit of a wart that people have to know about CompletionStage at all. They should just have to learn about completable future.

Agree. Calling it `getStage` was just because it's a Supplier<CompletionStage>, which was requested for integration with languages/libraries (Scala) where CompletionStage exists but CompletableFuture does not.
