### ISSUE TITLE
Implement Timeout policy

### ISSUE THREAD

**Issue by jhalterman** [jhalterman/failsafe#169]
For async, we use ForkJoinPool by default, currently with a CompletableFuture being used internally. Unfortunately, neither CompletableFuture or ForkJoinPool support cancel with interrupts for their tasks. So cancellation will only be effective for tasks waiting to be run.

- The Timeout policy should be configurable to support interrupts or not.
- The Timeout policy should (probably) fail with TimeoutException so that it can be bubbled up to outer policies and easily recognized by them as a failure (similar to CircuitBreakerOpenException).

**Comment by Tembrel** [comment]
What do you think about adding an `isCancelled` test to `ExecutionContext` to allow users to write more cancellation-responsive tasks by using the contextual methods?
```java
Failsafe.with(...).runAsync(ctx -> {
    while (...) {
        if (ctx.isCancelled()) throw ... // get out fast on cancellation
        // ...
    }
});
```

**Comment by jhalterman** [comment]
> What do you think about adding an isCancelled

Great idea.

Re: my initial comment: 

> Unfortunately, neither CompletableFuture or ForkJoinPool support cancel with interrupts for their tasks

I just pushed a commit (f54b7a0e4f37eb33e3d0a98558962d8d6cf9917b) that allows interruption of ForkJoinPool tasks. I thought pretty carefully about this implementation since interrupting FJP threads is probably unusual, but for the way we're using them it seems safe and appropriate, and should make Timeouts more useful for users who don't bring their own Scheduler. That said, definitely have a look at that commit if you're so inclined :)

**Comment by Tembrel** [comment]
Do we know for sure that ForkJoinPool implementations (especially the common pool) don't do something special to prevent interrupts? Looks like Doug Lea wrote tests for CompletableFuture specifically to ensure that interrupts in FJP threads would be ignored. (But if you have a test that demonstrates that it works on your platform, that's good enough for me.)

I don't think this handles the case of `getStageAsync(CheckedSupplier<CompletionStage>>)`, because Failsafe has no control over either the thread pool or the CompletionStage implementation in this case. For example,
```java
CompletableFuture<Result> f = Failsafe.with(policies)
    .getStageAsync(() -> CompletableFuture.supplyAsync(() -> {
        // code that checks interrupt status
        return result;
    });
```
I guess that's OK; there's a limit to what one can do to support cancellation via interrupt here, and `ExecutionContext.isCancelled` provides a bit of an out.

Nitpicking: Added a [comment about synchronization scope](https://github.com/jhalterman/failsafe/commit/f54b7a0e4f37eb33e3d0a98558962d8d6cf9917b#r32080918) to that commit.

**Comment by jhalterman** [comment]
As I'm working on this feature, a question has come up. A Timeout can be configured to cancel the underlying execution (optionally with interruption) if the timeout is exceeded:

```java
Timeout timeout = Timeout.of(Duration.ofSeconds(10)).withCancel(true);
Failsafe.with(retryPolicy, timeout).get(this::connect);
```

My question is, if an exception fails with a timeout that triggers a cancellation, should the execution be failed with `TimeoutException` or `CancellationException`? Since `Timeout`s will often be used with other policies such as RetryPolicy, it would be convenient if outer policies only needed to be concerned with handling `TimeoutException` and not anything else.

**Comment by whiskeysierra** [comment]
Maybe you can get some ideas from here? https://github.com/vsilaev/tascalate-concurrent#timeouts

It's different though because timeout there is an operator that creates a new future. The new one will complete with a timeout exception. The original one with a cancellation exception. In case of failsafe there is only one future that is visible to the outside, right?

**Comment by jhalterman** [comment]
Right now I'm thinking of always completing the execution with `TimeoutException` even if a separate cancellation is performed. The reason is that TimeoutException better represents why the execution failed. That it was cancelled in addition to timing out is a secondary effect to halt execution.

**Comment by jhalterman** [comment]
Closed via 371e051afa732f5aa2b297115a450375ce2e6dc0.

Added new sections to the docs on [execution cancellation](https://github.com/jhalterman/failsafe#execution-cancellation) and the [Timeout policy](https://github.com/jhalterman/failsafe#timeouts).

**Comment by jhalterman** [comment]
Feel free to try out the new policy. I'd like to release it in a day or so unless anything major seems wrong.

**Comment by jhalterman** [comment]
Something I'm still considering.... whether the `Timeout` policy should throw `java.util.concurrent.TimeoutException` (which is checked) or some other exception that extends RuntimeException. 

The problem with throwing `java.util.concurrent.TimeoutException` is that synchronous executions that timeout will actually have to throw FailsafeException that wraps TimeoutException as its cause, which is less convenient to use. CircuitBreakerOpenException is more convenient since you can catch it directly.

Thoughts?

**Comment by whiskeysierra** [comment]
Like `net.jodah.failsafe.TimeoutException`?

**Comment by whiskeysierra** [comment]
> On the other hand, in asynchronous land, everything you get from a Future is similarly wrapped in `ExecutionException`, and requires unwrapping.

As long as their is a synchronous way to execute something it should be as convenient as possible. (I'd actually get rid of the synchronous version in the long run since it's easier to learn and maintain a single API and making an asynchronous interface synchronous is relatively easy since you can either block or provide a fake executor.)

**Comment by jhalterman** [comment]
> net.jodah.failsafe.TimeoutException

Yep. I'm not 100% happy with that either though just because I'm sure some people will hit import conflicts with the class name being the same as the other TimeoutException.

> As long as their is a synchronous way to execute something it should be as convenient as possible

Meaning you would prefer not having TimeoutException wrapped inside a FailsafeException for sync executions?

**Comment by whiskeysierra** [comment]
> Meaning you would prefer not having TimeoutException wrapped inside a FailsafeException for sync executions?

Yes

**Comment by jhalterman** [comment]
How about 'TimeoutExpiredException'?

**Comment by whiskeysierra** [comment]
I like it. I saw a talk recently that advocated to name exceptions similar to events. They should have a notion of a verb and past tense in the name and removing the Exception suffix should actually not change the meaning. That name checks everything on the list.

**Comment by jhalterman** [comment]
👍 And it's somewhat symmetric with `CircuitBreakerOpenException` (though that might have been `CircuitBreakerOpenedException`...)

**Comment by whiskeysierra** [comment]
https://youtu.be/ZsHMHukIlJY 28:50, for the record

**Comment by jhalterman** [comment]
Good commentary on that point.

**Comment by jhalterman** [comment]
I'm actually thinking `TimeoutExceededException` is possibly a bit more accurate than expired.

**Comment by whiskeysierra** [comment]
True, good point

**Comment by jhalterman** [comment]
Timeouts are in master now. Will release in a day or so.

**Comment by jhalterman** [comment]
2.2.0 with timeouts has been released:

https://github.com/jhalterman/failsafe#timeouts
https://github.com/jhalterman/failsafe#execution-cancellation
