### ISSUE TITLE
ExecutorService + Wildfly

### ISSUE THREAD

**Issue by malys** [jhalterman/failsafe#174]
Since 2.0.1,  Failsafe supports ExecutorService.
I have tried to use ManagedExecutorService (JEE -Wildfly) to use FailSafe in WildFly.
The circuit break never switchs  to half-open state.

```
    private final CircuitBreaker<Object> circuitBreakerRuntime = new CircuitBreaker<>()
            .onOpen(this::openCircuit)
            .onClose(this::closeCircuit)
            .onHalfOpen(this::halfCircuit)
            .withFailureThreshold(2)
            .withSuccessThreshold(1)
            .withDelay(Duration.ofSeconds(10));
...
    @Resource
    private ManagedExecutorService managedExecutorService;

...
Failsafe
                .with(hsmFailureService.getCircuitBreakerRuntime(), hsmFailureService.getRetryPolicyInit())
                .with(managedExecutorService)
                .onSuccess(e -> log.debug("HSM is ONLINE"))
                .onFailure(e -> log.warn("Retrying FAILED"))
                .get(hsmConfigInitializer::initProvider);
```
Any ideas?

**Comment by Tembrel** [comment]
A couple of things strike me:

1. Are you sure you don't want `.getAsync(...)` instead of `.get(...)`?
1. The order you have the policies in:
   ```java
   .with(circuitBreaker, retryPolicy)
   ```
   means that the retry policy is applied __before__ the circuit breaker gets a chance to handle it. So there's no retrying at the outer level. (Or are you making multiple calls to `Failsafe.with(...)....get(...)` and getting to the open state but not the half-open state?)

**Comment by malys** [comment]
Hi,
I want to try twice to connect to external resources. (retry)
if it's OK I get the result of .get
else I catch the exception and circuit breaker is opened. => application throws event to  switch to offline mode.  
cb should to try to switch to online mode (using half-open state)

    `Failsafe.with(...)....get(...)` -> it calls one time
cb is opened but half state is never launched.

**Comment by Tembrel** [comment]
I'm not sure, but it sounds like you have the policies in the wrong order. Check [this section of the README](https://github.com/jhalterman/failsafe#policy-composition). Note that the failure threshold of 2 for the circuit breaker doesn't control retries, it just means that __if__ the circuit breaker is used twice in a row unsuccessfully, the circuit will open. Putting your retries __after__ the circuit breaker in the varargs parameters means that the circuit breaker only records the successes or failures that make it past the retry policy.

And I believe that by calling `.get(...)` at the end of your chain you are bypassing the use of the `ManagedExecutorService` entirely. Your call to `.with(managedExecutorService)` __sets__ the `scheduler` field of the `FailsafeExecutor` on which you are calling `get(...)`, but the `get(...)` itself uses an [Execution](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/Execution.java) instance internally rather than an [AsyncExecution](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/AsyncExecution.java) instance, and only the latter takes a `scheduler` argument.

Caveat lector: This code is pretty new, so I'm still shaky on the implementation details.

**Comment by jhalterman** [comment]
+1 to @Tembrel's comments. If you want to use an `ExecutorService` use `.getAsync`. Also, you might double check the order you have your policies in (see [this section](https://github.com/jhalterman/failsafe#policy-composition) in the docs).

According to your configuration, the CircuitBreaker will be opened after 2 successive failed executions, half-opened on the next execution after 10 seconds, and since the success threshold is 1 it will immediately transition to closed if that execution is successful, else back to open.

**Comment by Tembrel** [comment]
@jhalterman - Does this make you want to reconsider the `Failsafe.with(Policy...)` method? I confess it seems backwards to me, too; I was too chicken to speak up before.

**Comment by jhalterman** [comment]
Haha, yea I understand the concern. The short answer is I was setting things up to deal with some more complex policy composition scenarios that will come once we introduce additional policy implementations. Let me explain... :)

The inspiration for Failsafe's policy composition came from [Polly](https://github.com/App-vNext/Polly)'s [PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap) and wanting to support complex policy compositions which may include a mix of pre and post-execution behaviors. The key point is the idea that some policies might have pre-execution behaviors, such as a CircuitBreaker open check, a cache, or a timeout. Intuitively it would make sense to configure policies in the order that they're used, ex: circuit breaker first, then a retry policy. But that assumes that the policies only have post-execution behaviors. If they also are applied before an execution takes place, then that order doesn't really make sense and is hard to reason about.

For example, consider this rather large composition of hypothetical policies: 

```java
.with(fallback, cache, overallTimeout, retryPolicy, circuitBreaker, bulkhead, timeout).get(supplier);
```

This [timing diagram](https://user-images.githubusercontent.com/9608723/32406632-bb7d2a06-c173-11e7-8a83-3f07549eb819.PNG) from the Polly docs shows how an execution request flows through the policies. Starting from left to right, you can see that a request flows through the outermost policy, triggering any possible pre-execution behaviors before the runnable/supplier is finally called, then the result snakes its way back through the post-execution handling of the policies. The `.with` statement nicely mirrors the actual flow through the policies, working from the outside to the supplier then back again.

If we reverse the arrangement:

```java
.with(timeout, bulkhead, circuitBreaker, retryPolicy, overallTimeout, cache, fallback).get(supplier);
```

...the things become hard to reason about in a different way. Is `timeout` used first? Is `cache` used second? Since policies handle execution flow in both directions - before and after the supplier, using the composition approach seems the most straightforward to make sense of.

**Comment by malys** [comment]
Hi,
I will check my code and follow your advice.

**Comment by Tembrel** [comment]
@jhalterman - All understood, makes sense. I think it would help, though, to have method names that convey the directionality of the nesting. For example:
```java
Policy a, b, c;
Failsafe.wrappingOutward(a, b, c)       // c(b(a(x)))
Failsafe.wrappingInward(a, b, c)        // a(b(c(x)))
```
I like that PolicyWrap allows functional composition. Your stated reason for __not__ allowing this was to force the programmer to be aware of order, but if the names are suggestive enough, wouldn't that force awareness as well?
```java
Failsafe.with(a)
    .wrappedBy(b)
    .wrapping(c) // b(a(c(x)))
```
I realize that would complicate the API, because you couldn't then simply return `FailsafeExecutor` from the `.with(...)` call.

**Comment by jhalterman** [comment]
> Your stated reason for **not** allowing this was to force the programmer to be aware of order, but if the names are suggestive enough, wouldn't that force awareness as well?

Yea, being more explicit wouldn't be a bad thing, it would just be a bit more verbose. I would probably prefer to offer more explicit wrapping but only in one direction - inward:

```java
Failsafe.with(circuitBreaker)
  .wrapWith(retryPolicy)
  .wrapWith(fallback);
```

...since wrapping the other way is harder to reason about when considering pre and post execution behaviors in policies and wrapping in both directions is just more to explain. In this case `Failsafe.with(fallback, retryPolicy, circuitBreaker)` could still be shorthand but at least we'd have an explicit alternative to compare it to.

**Comment by malys** [comment]
Reading your comments (see [it](https://github.com/jhalterman/failsafe/issues/174#issuecomment-460753230))

> The important thing to know is that the CircuitBreaker only transitions when an execution occurs.
It was not a problem of asynchronous call but I must generate executions to enable half-open state. (tricky :))

Thx for your help.
