### ISSUE TITLE
Timeouts not getting passed 1 failure attempt

### ISSUE THREAD

**Issue by steppinrazor** [jhalterman/failsafe#194]
So I'm trying to get to the point where multiple long-running processes that exceed the timeout eventually end up in my fallback being triggered.

```java
CircuitBreaker<Object> cb = new CircuitBreaker<>()
                .handle(Exception.class)
                .withFailureThreshold(2)
                .withSuccessThreshold(2)
                .withTimeout(Duration.ofMillis(500))
                .withDelay(Duration.ofMillis(1000))
               .onFailure(e -> log.info("a failure occurred"));

RetryPolicy<Object> rp = new RetryPolicy<>()
                .handle(Exception.class)
                .withDelay(Duration.ofMillis(500))
                .withMaxRetries(2);

Failsafe.with(Fallback.of(() -> "fallback action"), rp, cb).get(() -> longRunningProcess());
```

So say `longRunningProcess()` runs for 2 seconds, and my timeout is 500 millis - in what scenario can the fallback be triggered after multiple long-running calls. 

Right now I can see `onFailure()` trigger but it is stuck on 1 failed attempt for multiple calls that take too long - why is the number of failed attempts not in-sync with the actual # of calls that took too long and then the falback should kick in?

**Comment by steppinrazor** [comment]
I can never trigger the fallback.

**Comment by jhalterman** [comment]
An important thing to note is that each policy makes its own determination about what is a failure. In this case the CircuitBreaker will consider an Exception (`handle(Exception.class)`) or an execution that exceeds 500 millis (`withTimeout`) to be a failure, The RetryPolicy will consider any exception a failure (`handle(Exception.class)`), and so will the Fallback (by default, policies treat any exception as a failure).

So when `longRunningProcess` first times out, the CircuitBreaker treats it as a failure, but the other policies will only treat it as a failure if it throws an exception. If `longRunningProcess` times out 2 times in a row (`withFailureThreshold(2)`) the CircuitBreaker will be opened and the RetryPolicy will kick in. The RetryPolicy will fail though since the CircuitBreaker will throw `CircuitBreakerOpenException` until 1000 millis have passed (`withDelay`). In this case that means the first retry will fail but the second one will succeed. Still, the CircuitBreaker treats the next `longRunningProcess` call as a failure, and we go in circles.

Here's some example code with a bit more logging that shows what happens:

```java
    CircuitBreaker<Object> cb = new CircuitBreaker<>().handle(Exception.class)
      .withFailureThreshold(2)
      .withSuccessThreshold(2)
      .withTimeout(Duration.ofMillis(500))
      .withDelay(Duration.ofMillis(1000))
      .onOpen(() -> LOG.info("Breaker opened"))
      .onHalfOpen(() -> LOG.info("Breaker half-opened"))
      .onFailure(e -> LOG.info("Failed circuit breaker execution " + e));

    RetryPolicy<Object> rp = new RetryPolicy<>().handle(Exception.class)
      .withDelay(Duration.ofMillis(500))
      .withMaxRetries(2)
      .onFailedAttempt(e -> LOG.info("Attempt failed " + e))
      .onFailure(e -> LOG.info("Failed retry policy " + e));

    for (int i = 0; i < 3; i++) {
      LOG.info("---");
      Object result = Failsafe.with(Fallback.of("fallback"), rp, cb).get(() -> {
        LOG.info("Doing work");
        Thread.sleep(600);
        return "slow";
      });

      LOG.info("Result: " + result);
    }
```

Running this results in:

```
[2019-07-31 14:44:59.766] --- 
[2019-07-31 14:44:59.786] Doing work 
[2019-07-31 14:45:00.389] Failed circuit breaker execution ExecutionCompletedEvent[result=slow, failure=null] 
[2019-07-31 14:45:00.389] Result: slow 
[2019-07-31 14:45:00.389] --- 
[2019-07-31 14:45:00.390] Doing work 
[2019-07-31 14:45:00.996] Breaker opened 
[2019-07-31 14:45:00.997] Failed circuit breaker execution ExecutionCompletedEvent[result=slow, failure=null] 
[2019-07-31 14:45:00.997] Result: slow 
[2019-07-31 14:45:00.997] --- 
[2019-07-31 14:45:00.998] Attempt failed ExecutionAttemptedEvent[result=null, failure=net.jodah.failsafe.CircuitBreakerOpenException] 
[2019-07-31 14:45:01.500] Attempt failed ExecutionAttemptedEvent[result=null, failure=net.jodah.failsafe.CircuitBreakerOpenException] 
[2019-07-31 14:45:02.004] Breaker half-opened 
[2019-07-31 14:45:02.005] Doing work 
[2019-07-31 14:45:02.610] Breaker opened 
[2019-07-31 14:45:02.611] Failed circuit breaker execution ExecutionCompletedEvent[result=slow, failure=null] 
[2019-07-31 14:45:02.611] Result: slow 
```

The way to resolve this is to make sure that the RetryPolicy and Fallback are configured to treat whatever comes back from `longRunningProcess` as a failure if that is necessary. One option is to have `longRunningProcess` throw an exception if it's slow, or you it could return some distinguished value to represent it being slow, which the other policies could be configured to recognize:

```java
retryPolicy.handleResult("slow")
```

Another option would be to enhance Failsafe to support something like this (which it currently doesn't support):

```java
retryPolicy.handleIf(ctx -> {
  return ctx.getElapsedTime.getElapsedTime().toMillis() > 500;
});
```

I'm happy to add support for that if it makes sense.

**Comment by steppinrazor** [comment]
Hmmm this would mean I have to essentially check for the timeout myself and really `.withTimeout(Duration.ofMillis(500))` doesn't help me in what I want to try to achieve. I'll have to figure out something since I need the fallback to get kicked in like it would for an exception.

**Comment by steppinrazor** [comment]
Seems kinda counter-intuitive though but thanks for your feedback.

**Comment by jhalterman** [comment]
@steppinrazor I'm happy to take any suggestion you have for how things could be improved. I'm curious, does `longRunningProcess` return a valid result eventually, it just takes a while? I'd like to understand the use case better, where we get a valid result but we want to retry anyways because it took too long.

One idea is that each policy could support timeouts. Since policies are independent of each other though, they would each need to be configured to recognize a timeout as a failure:

```
circuitBreaker.withTimeout
retryPolicy.withTimeout...
```
etc.

I'd like to understand if that makes sense for some use case though since retrying on a timeout where there was a valid result seems unusual.

**Comment by whiskeysierra** [comment]
Shouldn't timeouts become their own policy? So one would just register a
timeout policy around those policies that need one. Freeing the other
policy implementations from the burden to implement anew every time.

**Comment by jhalterman** [comment]
Yea, that's a good point. If timeout is the innermost policy, then that simplifies this kind of use case.

**Comment by jhalterman** [comment]
Added a `Timeout` policy that should make this easier next time:

https://github.com/jhalterman/failsafe#timeouts
