### ISSUE TITLE
Create CircuitBreaker and check for allowsExecution

### ISSUE THREAD

**Issue by danpersa** [jhalterman/failsafe#34]
```
CircuitBreaker breaker = new CircuitBreaker();
breaker.allowsExecution();
```

This code throws a NPE, as the state is still null.

**Comment by chhsiao90** [comment]
Maybe try breaker.initialize() before use it.
And I notice that the CircuitBreakerProvider in the referenced issue that seams solved this problem too.
```scala
break.open()
break.close()
```

But I think there is some other better way then throw NPE here.
- give the CircuitBreaker close state whenever a new CircuitBreaker create
- throw IllegalStateException when CircuitBreaker not initialized

**Comment by chhsiao90** [comment]
> Maybe try breaker.initialize() before use it.
Sorry, I hadn't noticed that this method is in package scope...
Currently, call close after open is the only way to use the CircuitBreaker in a standalone way

**Comment by danpersa** [comment]
yes, that's the workaround I used.

**Comment by jhalterman** [comment]
Thanks for filing. The appropriate workaround for now:

```
CircuitBreaker breaker = new CircuitBreaker();
breaker.close();
```

**Comment by chhsiao90** [comment]
Hi @jhalterman 

Currently, call breaker.close() just after constructor cannot work,
because breaker.close() will call transitionTo that will determine that the new state is same as previous state, so it would not change the state to closed and still remain the state be null.

I had some modification on this.
Please see [2400b2e24f128ca5d9291daf11d95fe048782f7e](https://github.com/chhsiao90/failsafe/commit/2400b2e24f128ca5d9291daf11d95fe048782f7e)
- Allow close() call just after construct
- Add unit test on CircuitBreaker   
_Because the document said that it's recommended to used CircuitBreaker in standalone way,
so I think only test on how CircuitBreak be config seams not enough, so I had some additional test on it_
- Removed unused if (state != null) because the state will always not be null
- Throw IllegalStateException while state is not in a consist state
 
The commit still not ready for PR.
Though the test is pass, but I should make sure that there is no side effect was bring in.
And I will need more time to add more test on CircuitBreaker.

**Comment by jhalterman** [comment]
Hi @chhsiao90

I was actually working on this too... I think what I'd like is for `CircuitBreaker` to default to closed state. With the current code, we can't just close() the circuit after construction though because it still needs to be configured (ex: `withSuccessThreshold`) since the configuration is used by the `ClosedState`. Once I fix this, later today, I'll push my changes. I'd like to still pickup your test cases though since those look good, if you want to submit them afterwords.

**Comment by chhsiao90** [comment]
Got it, I will help about the unit test after you!

**Comment by danpersa** [comment]
I like the idea with having the default state to closed.

**Comment by chhsiao90** [comment]
Hi @jhalterman

I just find that how CircuitBreaker change d unit test had bean wrote at the state test, like OpenStateTest.
And it seems good enough for this situation.

**Comment by jhalterman** [comment]
`CircuitBreaker` now defaults to closed and can be reconfigured (via `withSuccessThreshold`, `withFailureThreshold`) at any time. Any executions that were recorded from a prior configuration will be carried over.
