### ISSUE TITLE
Question: CircularBitSet.java#L33

### ISSUE THREAD

**Issue by na389** [jhalterman/failsafe#38]
Why occupiedBits - size and not the other way around?

**Comment by kinow** [comment]
Permanent link for the code mentioned https://github.com/jhalterman/failsafe/blob/119c6c88a82df906134ab1b06459fe8bebdadaf0/src/main/java/net/jodah/failsafe/internal/util/CircularBitSet.java#L33
(won't change after a commit)

**Comment by chhsiao90** [comment]
Hi @na389 ,

Because CircularBitSet should keep **latest** execution result while the threshold size became smaller.  
ex:
while CircularBitSet size changed from 10 to 4, the new CircularBitSet will only take the execution result from old bitSet from 6 to 10.

**Comment by jhalterman** [comment]
@na389 I just pushed a commit that re-works this a bit, so hopefully it's clear now what's going on. The basic algo is:

* Determine how many bits to copy.
* Determine the index to start copying from.
* Loop and copy the bits. Since the data structure is circular, looping may require going back to `0`.

Since we want to copy the `n` most recent bits, [the start index](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/internal/util/CircularBitSet.java#L37-L39) is just the end of the logical bitset (`nextIndex`) minus the number of bits to copy. But since the data structure is circular, if this number ends up being negative (when the number of bits to copy is greater than the `nextIndex), then we need to offset by the size of the bitset.

You can check out some of the [test cases](https://github.com/jhalterman/failsafe/blob/master/src/test/java/net/jodah/failsafe/internal/util/CircularBitSetTest.java#L53-L87) for this stuff which assert copied results with various `nextIndex` values (which would vary as the circular BitSet is filled and refilled).
