### ISSUE TITLE
Standalone CircuitBreaker doesn't respect withDelay configuration

### ISSUE THREAD

**Issue by Spikhalskiy** [jhalterman/failsafe#50]
There is a note about [standalone usage](https://github.com/jhalterman/failsafe#standalone-usage) of CircuitBreaker in docs, but in this usage ```withDelay(long delay, TimeUnit timeUnit)``` configuration is not respected, which is not obvious. Would be great to support delay inside CircuitBreaker, but at least add a javadoc to ```withDelay``` that this method doesn't make any sense for standalone usage.

**Comment by jhalterman** [comment]
`withDelay` should always work, even when manually operating the CircuitBreaker. State transitions occur when `CircuitBreaker.allowsExecution` is called. If the delay has been exceeded since the circuit breaker has been in that state, then a transition will happen. Here's a bit of code that demonstrates:

```
  public void test() throws Throwable {
    CircuitBreaker breaker = new CircuitBreaker().withDelay(500, TimeUnit.MILLISECONDS);
    
    breaker.open();
    breaker.allowsExecution();
    Thread.sleep(400);
    
    assertTrue(breaker.isOpen());
    Thread.sleep(150);
    breaker.allowsExecution();
    assertTrue(breaker.isHalfOpen());
  }
```

Are you seeing something else?

**Comment by Spikhalskiy** [comment]
Ups, I didn't use this method, it's pretty unobvious that this method triggers state changing and getState doesn't. Maybe additional javadocs for getState() that if you want state to be updated - you should trigger ```allowsExecution()``` before in case of standalone usage? Thanks for your help anyway.

**Comment by jhalterman** [comment]
No problem. `getState()` triggering a transition is not a bad idea. Standalone usage is a bit more of a niche use case, but I want it to make sense.

**Comment by jhalterman** [comment]
@Spikhalskiy What would your ideal API/usage look like?

**Comment by Spikhalskiy** [comment]
@jhalterman I already can't adopt canonical failsafe API to my project, because we have some different requirements like... in half_open state we don't want to allow any concurrent executions, we want to allow only one execution for health check and only after success of this one execution allow concurrency for this service. But CircuitBreaker alone is very fine for me.

Give me some time, maybe I would back with some pull requests and proposals. Thank you for response.

**Comment by jhalterman** [comment]
@Spikhalskiy Your comments are welcome and appreciated.

I have thought about supporting limited concurrency in half-open state (see #44), but haven't heard much from users on this so it wasn't a priority. Right now max concurrency is determined by the success and failure thresholds you set:

https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/internal/HalfOpenState.java#L92-L98

So you could set `.withSuccessThreshold(1)` and it sounds like that should work for your use case. The problem is that right now, tracking [currentExecutions](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/CircuitBreaker.java#L30) isn't really supported for standalone usage. For internal usage via the `Failsafe` class, failsafe calls `CircuitBreaker.before`, so something like that would need to be exposed for standalone usage to inform the breaker that an execution is about to be performed.
