### ISSUE TITLE
Support wrapping functions as Failsafe executions

### ISSUE THREAD

**Issue by jhalterman** [jhalterman/failsafe#80]
Something to consider, does it make sense to wrap executions as simple Callables, etc., which can be executed later in a Failsafe way?

```
Callable<Connection> connectWithRetries = Failsafe.with(retryPolicy).wrap(this::connect);
Connection connection = connectWithRetries.call();
```

**Comment by Tembrel** [comment]
Such a wrapper would typically change the semantics of the wrapped callable, because the possible return values and exceptions thrown could be quite different, depending on the retryPolicy supplied.  A simple case might be like this:
```java
Future<Integer> f = exec.submit(() -> Failsafe.with(retryPolicy).get(someCallable));
```
but more complicated situations could arise:
```java
Future<Integer> f2 = exec.submit(() -> {
    try {
	return Failsafe.with(breaker).get(anotherCallable);
    } catch (CircuitBreakerOpenException ex) {
	// log circuit breaker exception
	throw ex;
    } catch (FailsafeException ex) {
	if (ex.getCause() instanceof SomeExpectedException) {
	    throw (SomeExpectedException) ex.getCause();
	} else {
	    throw new RuntimeException("unexpected", ex);
	}
    }
});
```
That suggests that no single `wrap` implementation would suit all purposes. As is clear from these examples, it's not hard to package things for later execution anyway, so I don't think it's worth providing extra support for it within this library.

**Comment by jhalterman** [comment]
Hi @Tembrel -

You're right about Failsafe possibly changing the semantics of some execution: a fallback result can be substituted in for some failure result or a `FailsafeException` can take the place of a checked exception. This is true of the library in general, but I guess your point is that at least this behavior isn't hidden inside an innocent looking `Callable`? 

To me, I see this as just function composition, where we're decorating some `Callable` with additional behavior that might alter the result of the thing we're decorating. But to your point, is that's an argument against function composition in general or do you think it's different from this situation?

**Comment by Tembrel** [comment]
Any implementation of `wrap` is going to have to make choices about how to translate/propagate exceptions. Those choices aren't going to be right for all occasions and for all retry policies and circuit breakers, so at least some users are inevitably going to have to roll their own.

Rather than try to pick one best choice and enshrine it as `SyncFailsafe.wrap`, consider giving examples in the javadocs of different approaches to wrapping.

Here is one example, but you can imagine many different variations:
```java
// Wraps callable so that it retries on every exception except exType.
// The resulting callable can still throw exType.
<T, X extends Exception> Callable<T> wrap(Callable<T> callable, Class<X> exType) {
    RetryPolicy retryPolicy = new RetryPolicy()
	.retryOn(ex -> !exType.isInstance(ex));
    return () -> {
	try {
	    return Failsafe.with(retryPolicy).get(callable);
	} catch (FailsafeException ex) {
	    if (exType.isInstance(ex)) {
		throw ex;
	    } else {
		throw new RuntimeException("unexpected", ex);
	    }
	}
    };
}
```

**Comment by jhalterman** [comment]
@Tembrel I read through your comments a few times to make sure I'm not misunderstanding you. You mention:

> Any implementation of wrap is going to have to make choices about how to translate/propagate exceptions

True, but really, exception propagation would be consistent with the way exceptions are already translated/propagated in Failsafe. If an executable block fails with an exception and retries are exhausted or not supported for that exception, then the exception would be re-thrown from the `wrap`ed function in the same way that it would be for a `SyncFailsafe.run` call. Similar for `CircuitBreakerOpenException`.

It's true that a `Runnable`, without knowing its origin, could be seen as a black box, but that's true of any `Runnable`. And it is true that a Failsafe `wrap`ed Runnable may throw `CircuitBreakerOpenException` or `FailsafeException` instead of `SomeCheckedException`, but this is the same for `SyncFailsafe.run`.

IMO, the implementation of `SyncFailsafe.wrap` should be analogous to doing:

```
Runnable failsafeRunnable = () -> Failsafe.with(retryPolicy).run(this::connect);
```

...which is so simple its begs the necessity of a `wrap` method in the first place really :)

**Comment by Tembrel** [comment]
> IMO, the implementation of SyncFailsafe.wrap should be analogous to doing:
> ```
> Runnable failsafeRunnable = () -> Failsafe.with(retryPolicy).run(this::connect);
> ```
> ...which is so simple its begs the necessity of a wrap method in the first place really :)

Agreed. To use the Josh Bloch's terminology, adding `wrap` would decrease the *power-to-weight ratio* of the Failsafe API.
