### ISSUE TITLE
Support for Spring ThreadPoolTaskExecutor

### ISSUE THREAD

**Issue by mguilherme** [jhalterman/failsafe#98]
It would be nice to support other task executors besides `ScheduledExecutorService` and `Scheduler`.
Since I'm using **Spring** with AsyncTaskExecutor I cannot take full advantage of failsafe.

Suppose I have a bean:

```Java
@Bean
public AsyncTaskExecutor asyncExecutor() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
    executor.setCorePoolSize(5);
    executor.setMaxPoolSize(10);
    executor.setQueueCapacity(25);
    executor.setThreadNamePrefix("myExecutor-");

    return executor;
}
```

It would be nice to do something like:

```Java
Failsafe.with(retryPolicy)
                        .with(asyncExecutor())
                        .onFailedAttempt((o, throwable, context) ->
                                log.warn("Retrying, Message: {}, Attemp: {}", throwable.getMessage(), context.getExecutions())
                        )
                        .onFailure(throwable -> log.error("Failure, {}", throwable.getMessage()))
                        .withFallback(() -> log.info("Recovering"))
                        .run(() -> myService.doStuff());
```

Instead of:
```Java
asyncExecutor().execute(() ->
                Failsafe.with(retryPolicy)
                        .onFailedAttempt((o, throwable, context) ->
                                log.warn("Retrying, Message: {}, Attemp: {}", throwable.getMessage(), context.getExecutions())
                        )
                        .onFailure(throwable -> log.error("Failure, {}", throwable.getMessage()))
                        .withFallback(() -> log.info("Recovering"))
                        .run(() -> myService.doStuff())
        );
```

**Comment by jhalterman** [comment]
Hi @mguilherme 

I currently have no plans to support `ThreadPoolTaskExecutor` since this would require a dependency on Spring. The idea behind Scheduler is that it can be used to adapt other library's schedulers to be used in Failsafe. To make this a bit easier, Failsafe included a `DefaultScheduledFuture`. Have a look at this [Vert.x example](https://github.com/jhalterman/failsafe/blob/master/src/test/java/net/jodah/failsafe/examples/VertxExample.java#L38-L61) that includes a Scheduler implementation for Vert.x.

**Comment by whiskeysierra** [comment]
Spring's `ThreadPoolTaskExecutor` is just using Java's normal executors/schedulers under the hood. I'd just try to not use Spring's "abstraction" and use the traditional interfaces directly.
